describe('Scope tool Testing', () => {
    it('1.Scope tool login 2.Checking AT&T Cybersecurity,scope and Portfolios button 3.Checking Show all,only mine,completed, archived button 4.Dropdown options 5.Status filter 6.Validating search box 7.Scope tool page 8.Sending Validating and Archieving scope', () => {
      //To check if the user is able to land on scoping tool login page.
      //1.SCOPE TOOL (TC-> 1-8)
      
      //cybersecurity.att.com/order/scopes/login/')
      //cy.fixture('userData(suganya login).json').then((user) =>{
      //cy.get('#id_username').type(user.username)
      //cy.get('#id_password').type(user.password)
      cy.contains('Sign In')
      cy.contains('Username')
      cy.contains('Password')
      cy.contains('Forgot/Reset Password')
      cy.contains("Don't have access?")
      cy.contains('Request Scoping Tool Access')
      cy.contains('Login Tutorial')
      cy.wait(2000)
       //To check if the user is able to login with invalid data
      cy.fixture('userData(suganya login).json').then((user) =>{
      cy.get('#id_username')
      cy.get('#id_password').type(user.password)
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(1) div.col-md-6.offset-md-3 div.vstack.gap-3 div.bg-light:nth-child(1) form.my-4:nth-child(2) div.d-grid.gap-2:nth-child(4) > button.btn.btn-primary:nth-child(1)').click()
      cy.get('#id_password').clear()
      cy.get('#id_username').type(user.username)
      cy.get('#id_password')
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(1) div.col-md-6.offset-md-3 div.vstack.gap-3 div.bg-light:nth-child(1) form.my-4:nth-child(2) div.d-grid.gap-2:nth-child(4) > button.btn.btn-primary:nth-child(1)').click()
      cy.get('#id_username').clear()
      cy.wait(2000)
      //To check if the user is able to login with valid data
      cy.get('#id_username').type(user.username)
      cy.get('#id_password').type(user.password)
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(1) div.col-md-6.offset-md-3 div.vstack.gap-3 div.bg-light:nth-child(1) form.my-4:nth-child(2) div.d-grid.gap-2:nth-child(4) > button.btn.btn-primary:nth-child(1)').click()
      cy.wait(2000)

       //2.SCOPE TOOL HOME PAGE(TC-> 1-34)
      //checking for the elements in Home page.
      cy.contains('AT&T Cybersecurity')
      cy.contains('Scope')
      cy.contains('Portfolios')
      cy.contains('Active Portfolio')
      cy.contains('New Scope')
      cy.contains('Only Mine')
      cy.contains('Completed')
      cy.contains('Archived')
      cy.contains('In Progress')
      cy.contains('Show')
      cy.contains('entries')
      cy.contains('Status Filter')
      cy.contains('Actions')
      cy.contains('Status')
      cy.contains('Company name')
      cy.contains('Customer Name')
      cy.contains('Customer Email')
      cy.contains('Sales Rep')
      cy.contains('Need Help?')
      cy.contains('logout')
      //To Check if page redirects to at&t cybersecurity landing page when user clicks on AT&T Cybersecurity link
      cy.get('body:nth-child(2) header.p-3.bg-primary:nth-child(1) div.container div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start > a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none').click()
      cy.contains('AT&T Cybersecurity')
      cy.contains('Scope')
      cy.contains('Portfolios')
      cy.contains('Active Portfolio')
      cy.contains('New Scope')
      cy.contains('Only Mine')
      cy.contains('Completed')
      cy.contains('Archived')
      cy.contains('In Progress')
      cy.contains('Show')
      cy.contains('entries')
      cy.contains('Status Filter')
      cy.contains('Actions')
      cy.contains('Status')
      cy.contains('Company name')
      cy.contains('Customer Name')
      cy.contains('Customer Email')
      cy.contains('Sales Rep')
      cy.contains('Need Help?')
      cy.contains('logout')
     //To Check if page redirects to at&t cybersecurity landing page when user clicks on Scope Button
      cy.get('body:nth-child(2) header.p-3.bg-primary:nth-child(1) div.container div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start > a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none').click()
      cy.contains('AT&T Cybersecurity')
      cy.contains('Scope')
      cy.contains('Portfolios')
      cy.contains('Active Portfolio')
      cy.contains('New Scope')
      cy.contains('Only Mine')
      cy.contains('Completed')
      cy.contains('Archived')
      cy.contains('In Progress')
      cy.contains('Show')
      cy.contains('entries')
      cy.contains('Status Filter')
      cy.contains('Actions')
      cy.contains('Status')
      cy.contains('Company name')
      cy.contains('Customer Name')
      cy.contains('Customer Email')
      cy.contains('Sales Rep')
      cy.contains('Need Help?')
      cy.contains('logout')
      //To Check if page redirect to ' Portfolios page' when user clicks on ' Portfolios ' link'
    cy.get('header.p-3.bg-primary:nth-child(1) div.container div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0.mx-4 li:nth-child(2) > a.nav-link.px-2.text-white').click()
    cy.wait(3000)
    cy.contains('AT&T Cybersecurity')
    cy.contains('Scope')
    cy.contains('Portfolios')
    cy.contains('Scope Portfolio')
    cy.contains('New Scope Portfolio')
    cy.contains('Show')
    cy.contains('Search')
    cy.contains('Name')
    cy.contains('Products')
    cy.contains('logout')

    //Mssp link
    cy.get('header.p-3.bg-primary:nth-child(1) div.container div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0.mx-4 li:nth-child(3) > a.nav-link.px-2.text-white')
    cy.wait(2000)
    cy.get('body:nth-child(2) header.p-3.bg-primary:nth-child(1) div.container div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start > a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none')
    cy.wait(2000)
    //To check if the user is able to see the all populated options while clicking on show all button

    cy.get('body:nth-child(2) header.p-3.bg-primary:nth-child(1) div.container div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start > a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none').click()

    cy.wait(3000)
    cy.get('#onlyMineToggle').click()
    cy.wait(3000)
    cy.get('header').click()
    cy.wait(3000)

    //To check respective user created scopes only  displayed while clicking on Only Mine button

    cy.get('#onlyMineToggle').click()
    cy.wait(3000)
    cy.get('header').click()
    cy.wait(3000)

    //To check if the user is able to see the completed status scope while clicking on Completed button

    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.btn-toolbar.mb-3:nth-child(4) div.btn-group.me-2:nth-child(2) div.stateGroup div.btn-group > button.btn.btn-default:nth-child(2)').click({force: true})
    cy.wait(3000)
    cy.contains('Validation Completed')

    //To check if the user is able to see the Archived status scope while clicking on Archived button'

    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.btn-toolbar.mb-3:nth-child(4) div.btn-group.me-2:nth-child(2) div.stateGroup div.btn-group > button.btn.btn-default:nth-child(3)').click({force:true})
    cy.wait(5000)
    cy.contains('Archived')

    //To Check if the user is able to select respective entries from Show dropdown list (10, 50, 25,100) 

    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_length label:nth-child(1) > select.form-select.form-select-sm')
    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_length label:nth-child(1) > select.form-select.form-select-sm').select(0)
    cy.wait(3000)
    cy.contains('10')
    cy.get('header').click()
    cy.wait(3000)
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_length label:nth-child(1) > select.form-select.form-select-sm').select(1)
    cy.wait(3000)
    cy.contains('25')
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_length label:nth-child(1) > select.form-select.form-select-sm').select(2)
    cy.wait(3000)
    cy.contains('50')
    cy.scrollTo('bottom')
    cy.wait(1000)
    cy.get('header').click()
    cy.wait(3000)
    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_length label:nth-child(1) > select.form-select.form-select-sm').select(3)
    cy.wait(3000)
    cy.get('header').click()
    cy.wait(3000)

    //To Check if the user is able to select respective status from Status filter list

    cy.get('#scopeStateFitler').select(0)
        cy.wait(3000)
        cy.contains('No Selection')
        cy.get('header').click()
        cy.wait(3000)
       
        cy.get('#scopeStateFitler').select(1)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Created')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(2)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Sent To Customer')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(3)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Customer Submitted')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(4)
        cy.get('header').click()
        cy.contains('Sent For Validation')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(5)
        cy.get('header').click()
        cy.contains('Valid with Limitations')
        cy.wait(3000)
        cy.get('header').click()
       
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(6)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Limitation Response')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(7)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Validation Complete')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(8)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Validation Denied')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(9)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Closed')

        
       
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(10)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Archived')
        cy.wait(3000)
        cy.get('#scopeStateFitler').select(11)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Not Interested')
        cy.wait(3000)
        //cy.wait(4000)
        cy.get('#scopeStateFitler').select(12)
        cy.wait(3000)
        cy.get('header').click()
        cy.contains('Closed Won')
        cy.wait(3000)

        //MSSP account filter 

        cy.get('#scopeAccountFitler').select(0)
        cy.wait(2000)
        cy.get('#scopeAccountFitler').select(1)
        cy.wait(2000)
        cy.get('#scopeAccountFitler').select(2)
        cy.wait(2000)
        cy.get('#scopeAccountFitler').select(0)
        cy.wait(2000)

        //To check valid result is shown while searching with valid data and To check error message is shown while searching with invalid data

         //valid data 
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_filter label:nth-child(1) > input.form-control.form-control-sm').type('qaoncloud')
         cy.wait(3000)
         cy.get('header').click()
         cy.wait(3000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_filter label:nth-child(1) > input.form-control.form-control-sm').clear()
         cy.wait(3000)
         //invalid data
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_filter label:nth-child(1) > input.form-control.form-control-sm').type('xyz')
         cy.wait(3000)
         cy.get('body:nth-child(2) header.p-3.bg-primary:nth-child(1) div.container div.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start > a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none').click()
         cy.wait(2000)
         //To check if previous, next and navigation buttons are working

         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_paginate.paging_simple_numbers ul.pagination li.paginate_button.page-item:nth-child(3) > a.page-link').click({force: true})
         cy.wait(3000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_paginate.paging_simple_numbers ul.pagination li.paginate_button.page-item:nth-child(4) > a.page-link').click({force: true})
         cy.wait(3000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_paginate.paging_simple_numbers ul.pagination li.paginate_button.page-item:nth-child(5) > a.page-link').click({force: true})
         cy.wait(3000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_paginate.paging_simple_numbers ul.pagination li.paginate_button.page-item:nth-child(6) > a.page-link').click({force: true})
         cy.wait(3000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.dataTables_paginate.paging_simple_numbers ul.pagination li.paginate_button.page-item:nth-child(7) > a.page-link').click({force: true})
         cy.wait(3000)

         ////SCOPE TOOL SCOPE PAGE & SEND SCOPE (TC-> 1-31)
         //To check if the user is able to create the new scope with invalid and valid data

         cy.get('#newScopeButton').click()
         cy.contains('Customer Information')
         cy.contains('Customer name')
         cy.contains('Customer email')
         cy.contains('Company name')
         cy.contains('Portfolio and Product')
         cy.contains('Portfolio being sold')
         cy.contains('Salesforce opportunity id')
         cy.contains('AT&T Internal')
         cy.contains('Sales Representative')
         cy.contains('Sales Expert')
         cy.wait(3000)
         cy.get('#saveScope').click()
         cy.scrollTo('top')
         cy.wait(3000)
         cy.contains('Customer email is required.')
         cy.contains('Customer name is required.')
         cy.contains('Product being sold is required.')
         cy.contains('Sales representative has not been set properly.')
         cy.wait(2000)
         cy.get('#id_customer_name').type('at&t')
    cy.get('#id_customer_email').type('avtesting07@qaoncloud.com')
    cy.get('#id_company_name').type('dc')
    //using ID 
    cy.get('body.modal-open:nth-child(2) div.container:nth-child(2) main.my-4 div.modal.fade.show:nth-child(13) div.modal-dialog.modal-lg div.modal-content div.modal-body form:nth-child(3) > div.unboxed-fields:nth-child(9)').click()
    cy.get('#id_product_being_sold').select('USM Anywhere')
    cy.wait(2000)
    cy.get('#id_product_being_sold').select('AT&T MTDR')
    cy.wait(2000)
    cy.get('#id_product_being_sold').select('USM Anywhere-MSSP')
    cy.wait(2000)
    cy.get('#id_product_being_sold').select('Penetration Test')
    cy.wait(2000)
    cy.get('#id_product_being_sold').select('USM Anywhere')
    cy.wait(2000)
    cy.get('#scope_version_selection').select('AT&T MTDR_Scoping_Luck Companies_090321.xlsx')
    cy.wait(2000)
    cy.get('#scope_version_selection').select('USM Anywhere_Scoping_Phoenix Color_101821.xlsx')
    cy.wait(2000)
    cy.get('#scope_version_selection').select('AT&T MTDR_Scoping_desi_030822.xlsx')
    //cy.wait(3000)
    //cy.get('#scope_version_selection').select('4')
    //cy.wait(3000)
    //cy.get('#scope_version_selection').select('5')
    //cy.wait(3000)
    //cy.get('#scope_version_selection').select('6')
    //cy.wait(3000)
    //cy.get('#scope_version_selection').select('7')
    //cy.wait(3000)
    //cy.get('#scope_version_selection').select('8')
    //cy.wait(3000)
    cy.get('#id_salesforce_override').select('Cybersecurity-Consulting')
    cy.wait(3000)
    cy.get('#id_salesforce_override').select('CyberSandbox')
    cy.wait(3000)
    cy.get('#sales_rep_typeahead').type('QA test ()')
    cy.get('#saveScope').click()

    //Send scope to customer, open validation , Archive scope 
    cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.DTFC_ScrollWrapper div.DTFC_LeftWrapper div.DTFC_LeftBodyWrapper div.DTFC_LeftBodyLiner table.table.table-sm.table-striped.table-condensed.table-bordered.table-hover.dataTable.no-footer.DTFC_Cloned tbody:nth-child(2) tr.odd:nth-child(1) td.dt-center div.btn-group.scopeActions > button.sendEmailButton.btn.btn-xs.btn-outline-primary').click({force: true})
    cy.wait(3000)
    // Sending scope
    cy.scrollTo('top')
    cy.contains('Email the Scope to the Customer')
    cy.contains('Subject')
    cy.contains('Message')
    cy.contains('You must have the token {{ link }} in your message to successfully send the email.')
    cy.get('#sendEmail').click()
    //opening validation
        cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.DTFC_ScrollWrapper div.DTFC_LeftWrapper div.DTFC_LeftBodyWrapper div.DTFC_LeftBodyLiner table.table.table-sm.table-striped.table-condensed.table-bordered.table-hover.dataTable.no-footer.DTFC_Cloned tbody:nth-child(2) tr.odd:nth-child(1) td.dt-center div.btn-group.scopeActions > button.openValidation.btn.btn-xs.btn-outline-primary').click({force: true})
        //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.DTFC_ScrollWrapper div.DTFC_LeftWrapper div.DTFC_LeftBodyWrapper div.DTFC_LeftBodyLiner table.table.table-sm.table-striped.table-condensed.table-bordered.table-hover.dataTable.no-footer.DTFC_Cloned tbody:nth-child(2) tr.odd:nth-child(1) td.dt-center div.btn-group.scopeActions > button.openValidation.btn.btn-xs.btn-outline-primary')
        cy.wait(3000)
        // archive scope 
        //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(12) div.col div.dataTables_wrapper.dt-bootstrap5.no-footer:nth-child(5) div.toolbar div.DTFC_ScrollWrapper div.DTFC_LeftWrapper div.DTFC_LeftBodyWrapper div.DTFC_LeftBodyLiner table.table.table-sm.table-striped.table-condensed.table-bordered.table-hover.dataTable.no-footer.DTFC_Cloned tbody:nth-child(2) tr.odd:nth-child(1) td.dt-center div.btn-group.scopeActions > button.archiveBtn.btn.btn-xs.btn-outline-danger').click()
        cy.wait(3000)

        Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      }
      )}
    )})})